//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKMISApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AC_AccountsEntry
    {
        public long ID { get; set; }
        public Nullable<long> BeneficiaryID { get; set; }
        public Nullable<long> CtgItemID { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsApproved { get; set; }
    
        public virtual AC_CategoryItem AC_CategoryItem { get; set; }
        public virtual UnitMaster UnitMaster { get; set; }
        public virtual VendorMaster VendorMaster { get; set; }
    }
}
