//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKMISApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeneficiaryEntry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BeneficiaryEntry()
        {
            this.BeneficiaryDocuments = new HashSet<BeneficiaryDocument>();
        }
    
        public long ID { get; set; }
        public string AllotmentNo { get; set; }
        public string BeneficiaryName { get; set; }
        public Nullable<long> MobileNo { get; set; }
        public Nullable<long> AadharNo { get; set; }
        public string WardName { get; set; }
        public Nullable<int> ConstituencyID { get; set; }
        public Nullable<int> BlockID { get; set; }
        public string GPUName { get; set; }
        public Nullable<int> ADCID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string FormID { get; set; }
        public Nullable<bool> IsSyncFromCloud { get; set; }
        public Nullable<bool> IsSyncToCloud { get; set; }
    
        public virtual ADCMaster ADCMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BeneficiaryDocument> BeneficiaryDocuments { get; set; }
        public virtual BlockMaster BlockMaster { get; set; }
        public virtual ConstituencyMaster ConstituencyMaster { get; set; }
    }
}
