//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKMISApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Progress
    {
        public int ID { get; set; }
        public Nullable<int> BeneficiaryID { get; set; }
        public string FormID { get; set; }
        public Nullable<bool> SiteLevellingProtectiveWork { get; set; }
        public Nullable<bool> UptoPlinthSlab { get; set; }
        public Nullable<bool> CastingOfSlab { get; set; }
        public Nullable<bool> SepticTank { get; set; }
        public Nullable<bool> HandOver { get; set; }
        public Nullable<bool> BrickPlasterWork { get; set; }
        public Nullable<bool> DoorWindows { get; set; }
        public Nullable<bool> ElectrificationPlumbing { get; set; }
        public Nullable<bool> PaitingFinishing { get; set; }
        public Nullable<System.DateTime> DateOfCommencement { get; set; }
        public Nullable<System.DateTime> DateOfCompletion { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
