//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKMISApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorEntry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VendorEntry()
        {
            this.VehicleEntries = new HashSet<VehicleEntry>();
        }
    
        public long VendorId { get; set; }
        public string VendorName { get; set; }
        public string VendorAddress { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public byte[] UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string State { get; set; }
        public Nullable<long> PinCode { get; set; }
        public Nullable<long> MobileNo { get; set; }
        public Nullable<long> PhoneNo { get; set; }
        public Nullable<long> Fax { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Misc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleEntry> VehicleEntries { get; set; }
    }
}
